project:
  type: website

  preview:
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  output-dir: docs
  execute-dir: project

  render:
    - "*.qmd"
    - "*.md"
    - "*.ipynb"
    - "!projects/"
    - "!tutorial/"

  resources:
    - "files/**"
    # Things that need to be at the site root
    - ".htaccess"
    - "LiveSearchSite.xml"
    # - "keybase.txt"
    - "y_key_31e0c4105fc75710.html"
    - "pgp_ath.asc.txt"

website:
  title: ""
  image: "/files/profiles/bottts-1774764655644.png"
  favicon: "/files/profiles/bottts-1774764655644.png"
  description: ""
  search:
    location: navbar
    type: overlay
  site-url: "https://grgrzhong.github.io/"
  repo-url: "https://github.com/grgrzhong/quarto"
  back-to-top-navigation: true
  page-navigation: true
  navbar:
    pinned: true
    left:
      - text: "About"
        file: "index.qmd"
      - text: "Blog"
        file: "blog/index.qmd"
      - text: "Linux"
        file: "linux/index.qmd"
      - text: "Python"
        file: "python/index.qmd"
      - text: "R"
        file: "r/index.qmd"
      - text: "Keymap"
        file: "keymap/index.qmd"
      - text: "Tools"
        file: "tools/index.qmd"
      - text: "10xGenomics"
        file: "omics/10xgenomics/index.qmd"
      - text: "Illumina"
        file: "omics/illumina/index.qmd"
  page-footer:
    center: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2021-2026 Guorui Zhong ~ Made with [{{< fa brands r-project >}}](https://www.r-project.org/), [{{< fa brands python >}}](https://www.python.org/) and [Quarto](https://quarto.org/)</span>

execute:
  freeze: auto # Prevent re-execution of code cells unless the code or its dependencies have changed
  eval: true # Enable code execution
  warning: false # Suppress warnings in output
  error: false # Suppress errors in output
  message: false # Suppress messages in output
  echo: true # Show code in output
  include: true # Include code output in output

format:
  html:
    theme:
      - html/me.scss
    grid:
      body-width: 900px
    toc: true
    toc-depth: 3
    toc_float: true
    toc-location: left
    number-sections: false
    number-depth: 3
    code-link: true
    code-fold: false # true to enable code folding
    code-overflow: wrap # scroll/wrap
    code-line-numbers: false
    df-print: default # default/kable/tibble/paged for data frame printing
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    smooth-scroll: true
    code-tools:
      source: true
      toggle: true
    highlight-style: dracula